### ISSUE TITLE
Bootstap model and determine correct p-values for segment().model_1()

### ISSUE THREAD

**Issue by austinPeel0** [GSA/travel-project-report#4]
Step 1:
get the latest segment.csv data from team drive.

step 2: 
use analysis/segment_analysis.py  to get started there are two models in there. They use  different specification of booking lead time. A log transformed version and a standarized version. I didnt know if I could log a standarized version since it would be weird with the 0s and getting back to normal

**Comment by csmcallister** [comment]
Here's my plan.

I'll randomly sample with replacement from our dataset about 10k times. 

For each sample, I'll fit the model that you've already specified. 

After I've fit that model, I'll save the summary (coefficients and p-values and standard errors). Then I'll plug in a single "new" observation to get a predicted value. When creating each of these "new" observations, I'll use a constant for all of the control variables (i.e. the mean for continuous predictors and the mode for the dummies), but then I'll use random values for the interaction term of `fair_type:booking_lead_time` that we're interested in. 

At the end of 10k iterations, we'll have a mapping of 10k model summaries to their predicted values and `fair_type:booking_lead_times` inputs. 

Once we have that mapping, we can plot the results two ways
 - With the predicted values, we can have 4 fitted lines, one for each fare type, with the y-axis being the predicted value and the x-axis being the booking lead time. We could plot the confidence interval for each line as well.
 - With the p-values/errors/coefficients, we can plot/describe the confidence intervals.

I'll confirm this approach with the MS team tomorrow and update you.

**Comment by csmcallister** [comment]
Here's the plot of predicted values against booking lead times for the four fare types. 

<img width="1013" alt="Screen Shot 2019-06-04 at 10 39 44 AM" src="https://user-images.githubusercontent.com/33464354/58888728-d909a000-86b5-11e9-9dc0-29d09a5c4fde.png">

**Comment by csmcallister** [comment]
Here's the same graph but with the log transformed data. **Note:  the plot colors are not consistent across the graphs.**

<img width="931" alt="Screen Shot 2019-06-04 at 1 32 49 PM" src="https://user-images.githubusercontent.com/33464354/58900549-5bea2500-86cd-11e9-9e1a-7df8d6bed2b4.png">

**Comment by csmcallister** [comment]
Also, I emailed Jasper asking about our approach. I _think_ I might need to adjust the bootstrap method so that it resamples from the individual traveler level as opposed to the row-level.

**Comment by austinPeel0** [comment]
We will need to use actual days for the log transformed version to show the curve.  Thank you for emailing him and all the help!

**Comment by csmcallister** [comment]
@austinPeel0 I'm going to need the traveler's name or ID in the dataframe in order to cluster bootstrap. I've created some fake travelers in the meantime, but could you update your model module so that `df` includes a column with the traveler's name or some other sort of unique identifier:

```python
from models.models import Segment 

#Using model 1
model = Segment().model_1()

#this is the data we are using 
df = model.model_data
```

**Comment by austinPeel0** [comment]
It might be easier for you to do it since you wont have to pull the code and fuss with github. 
In models/columns.py there is a dictionary for segment_columns just change to this:

EMAIL': {'description':'','source':'','type':'','keep':True},
